# Generated by Django 5.1.4 on 2024-12-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_blogpage_authors_remove_blogpage_page_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='FooterText',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='FormPage',
        ),
    ]
